language: bash
env:
  global:
    - TFLINT_VER='v0.7.0'
    - TERRAFORM_VER='0.11.7'
branches:
  only:
  - master
before_install:
  # Install tflint
  - "wget https://github.com/wata727/tflint/releases/download/${TFLINT_VER}/tflint_linux_amd64.zip"
  - "unzip tflint_linux_amd64.zip && chmod +x tflint"
  # Install Terraform
  - "wget https://releases.hashicorp.com/terraform/0.11.7/terraform_${TERRAFORM_VER}_linux_amd64.zip"
  - "unzip terraform_${TERRAFORM_VER}_linux_amd64.zip && chmod +x terraform"
script:
  # Test case
  # 1. tflint
  - "ls -l"
  - "./tflint"
  # 2. terraform init and fmt
  - "scripts/test_terraform.sh"
    
notifications:
  email: false
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - 'Commit message : %{commit_message}'
    rooms:
      secure: "YuQMcUg4UV/ZiA16I2hooYpRGLxd67UGGayGywT34RRvy6HmxAo3s9v1OdJb9TX6s9ldjnLiTHIbgZjuKpa/its3hzYLuG0B8yveWgceHTk5TdVk0uv375rfiG2973FXe12YB2cDnKixQKAY3EbKb5m1fS2VI23eBsh8AVwJ/+KG/+FYXBOS11ezaQJ/vdi/fmGpR73wU5udJisA3nMIFCAodQfvQeyV1TAn8B5UDrBykoEJ4C4dYoTupQ10V0DM1JTvQX+DmzZGXf8sAAc9ln/DWvUkrYscwnGatUqRAUPWV4Qw8fUzj0qPGgnIy8OmRsMk4bqjcVnub3wah8Jv/x6KHZ0Cy8hgxARUW4tgiISxbfhpW0SCBbqFDnesm+LL/EXkzoC9vktd3+MIuwMZleeFkgCwI+GQdwsZwyUQhjSWS+TLOPYAx7D1PuyceGbJNwukoe0k8gRbQKa4A79UEYUcmTRUWBbOdkrIucRNvdw5v8sx9s8Md/f9xbhcwNsiYQOQ5w9KXQF6Hx8mGvax3gJqW7nSLP0er5+mUK7Ly8pCK0uWG6H71t/ZVOt9kXXA75ThQesSVZSBFeCLvJdIUFLvrIdOC24vG4zDw3LPOOLoQAjk8CPZseFMS8E0paPX2fKXuFjOi7Dh5/88bT2XvE5wgHwIenqz633ZJSXc0TI="
